# Site settings
title: Code Is Not Cold
header-img: img/home-bg.jpg
email: hiaaronice@gmail.com
description: "Blog on technology, life, thinking, etc."
baseurl: ""
url: "aaronice.github.io"
twitter_username: ZibingH
github_username:  aaronice
## facebook_username:  zibing.huang
## linkedin: zibing

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ["jekyll-paginate"]
